version: '3'

services:
  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_PASSWORD: pass123
  #     POSTGRES_DB: your_postgres_database
  #     POSTGRES_USER: your_postgres_user

  mysql:
      image: mysql
      container_name: expense_tracker
      restart: unless-stopped

      ports:
          - 3306:3306

      environment:
          MYSQL_DATABASE: expense_tracker_db
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
