version: '3'

services:
  mysql:
      image: mysql
      container_name: expense_tracker
      restart: unless-stopped

      ports:
          - 3306:3306

      environment:
          MYSQL_DATABASE: expense_tracker_db
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
